### PR TITLE
feat: enable native postgres & Redshift

### PR DESCRIPTION
**Pull request by raphaelvignes**
Setup tests with fixtures for pypika translators.

### CODE REVIEW

**Comment by raphaelvignes** [comment]
Excluded tests for Redshift: 
```grep -lF 'redshift' tests/backends/fixtures/*/*
tests/backends/fixtures/aggregate/count_with_null.json
tests/backends/fixtures/aggregate/first.json
tests/backends/fixtures/aggregate/keep_original_granularity_empty_on.json
tests/backends/fixtures/aggregate/last.json
tests/backends/fixtures/aggregate/simple_aggregate_with_null.json
tests/backends/fixtures/aggregate/simple.json
tests/backends/fixtures/aggregate/snowflake_with_original_granularity.json
tests/backends/fixtures/aggregate/snowflake_with_original_granularity_multiple_aggregations.json
tests/backends/fixtures/aggregate/snowflake_with_original_granularity_multiple_aggregations_multiple_columns.json
tests/backends/fixtures/aggregate/with_original_granularity_multiple_aggregations.json
tests/backends/fixtures/aggregate/with_original_granularity_multiple_aggregations_multiple_columns.json
tests/backends/fixtures/append/domain_name_only.json
tests/backends/fixtures/append/simple.json
tests/backends/fixtures/append/with_domain_name.json
tests/backends/fixtures/comparetext/simple.json
tests/backends/fixtures/concatenate/simple.json
tests/backends/fixtures/convert/snowflake.json
tests/backends/fixtures/convert/to_bool.json
tests/backends/fixtures/convert/to_datetime_from_timestamp.json
tests/backends/fixtures/convert/to_datetime.json
tests/backends/fixtures/convert/to_float.json
tests/backends/fixtures/convert/to_integer_from_datetime.json
tests/backends/fixtures/convert/to_integer.json
tests/backends/fixtures/convert/to_integer_only_floats.json
tests/backends/fixtures/convert/to_integer_only_strings.json
tests/backends/fixtures/convert/to_text.json
tests/backends/fixtures/cumsum/simple.json
tests/backends/fixtures/cumsum/with_groups.json
tests/backends/fixtures/cumsum/with_multiple_values.json
tests/backends/fixtures/custom/simple.json
tests/backends/fixtures/customsql/simple.json
tests/backends/fixtures/dateextract/after_add_missing_dates_duplicate_values.json
tests/backends/fixtures/dateextract/all_cases.json
tests/backends/fixtures/dateextract/legacy_config.json
tests/backends/fixtures/dateextract/legacy_config_without_column.json
tests/backends/fixtures/dateextract/mongo_all_cases.json
tests/backends/fixtures/dateextract/snowflake_all_cases.json
tests/backends/fixtures/delete/non_existing_column.json
tests/backends/fixtures/dissolve/pandas_advanced.json
tests/backends/fixtures/dissolve/pandas_no_aggs.json
tests/backends/fixtures/dissolve/pandas_simple.json
tests/backends/fixtures/evolution/abs_nogroups.json
tests/backends/fixtures/evolution/perc_groups.json
tests/backends/fixtures/evolution/perc_nogroups.json
tests/backends/fixtures/filter/dates_from_until.json
tests/backends/fixtures/filter/dates_from_until_strip_hours.json
tests/backends/fixtures/filter/dates.json
tests/backends/fixtures/filter/relative_dates.json
tests/backends/fixtures/formula/division_zero.json
tests/backends/fixtures/formula/nested_divisions.json
tests/backends/fixtures/formula/special_col.json
tests/backends/fixtures/fromdate/day_longmonth_year_space.json
tests/backends/fixtures/fromdate/day_shortmonth_year_dash.json
tests/backends/fixtures/fromdate/day_shortmonth_year_space.json
tests/backends/fixtures/fromdate/longmonth_year_space.json
tests/backends/fixtures/fromdate/shortmonth_year_dash.json
tests/backends/fixtures/fromdate/shortmonth_year_space.json
tests/backends/fixtures/fromdate/simple.json
tests/backends/fixtures/fromdate/snowflake_simple.json
tests/backends/fixtures/hierarchy/pandas_advanced.json
tests/backends/fixtures/ifthenelse/dates-conditions.json
tests/backends/fixtures/ifthenelse/regex.json
tests/backends/fixtures/join/domain_name_only.json
tests/backends/fixtures/join/inner_geo_left.json
tests/backends/fixtures/join/inner_geo_right.json
tests/backends/fixtures/join/inner.json
tests/backends/fixtures/join/left_geo_left.json
tests/backends/fixtures/join/left_geo_right.json
tests/backends/fixtures/join/left.json
tests/backends/fixtures/join/left_outer.json
tests/backends/fixtures/movingaverage/simple.json
tests/backends/fixtures/movingaverage/with_groups.json
tests/backends/fixtures/percentage/advanced.json
tests/backends/fixtures/percentage/simple.json
tests/backends/fixtures/pivot/columns_cleaning.json
tests/backends/fixtures/pivot/simple.json
tests/backends/fixtures/rank/group_by.json
tests/backends/fixtures/rank/simple.json
tests/backends/fixtures/rank/snowflake.json
tests/backends/fixtures/replace/snowflake_simple.json
tests/backends/fixtures/rollup/groupby.json
tests/backends/fixtures/rollup/no_aggregation.json
tests/backends/fixtures/rollup/simple.json
tests/backends/fixtures/select/simple.json
tests/backends/fixtures/simplify/pandas_simple.json
tests/backends/fixtures/statistics/all.json
tests/backends/fixtures/todate/automatic_guess.json
tests/backends/fixtures/todate/from_timestamp.json
tests/backends/fixtures/todate/int_as_year_with_automatic_guess.json
tests/backends/fixtures/todate/simple.json
tests/backends/fixtures/todate/str_as_year_with_automatic_guess.json
tests/backends/fixtures/top/snowflake.json
tests/backends/fixtures/top/with_groups.json
tests/backends/fixtures/totals/simple.json
tests/backends/fixtures/totals/simple-pandas.json
tests/backends/fixtures/unpivot/pandas.json
tests/backends/fixtures/unpivot/snowflake.json
tests/backends/fixtures/waterfall/mywaterfall.json
tests/backends/fixtures/waterfall/simple.json
tests/backends/fixtures/waterfall/with_aggregation.json
tests/backends/fixtures/waterfall/with_groups.json
```

**Comment by raphaelvignes** [comment]
Excluded tests for postgres: 
```tests/backends/fixtures/aggregate/count_with_null.json
tests/backends/fixtures/aggregate/first.json
tests/backends/fixtures/aggregate/keep_original_granularity_empty_on.json
tests/backends/fixtures/aggregate/last.json
tests/backends/fixtures/aggregate/simple_aggregate_with_null.json
tests/backends/fixtures/aggregate/simple.json
tests/backends/fixtures/aggregate/snowflake_with_original_granularity.json
tests/backends/fixtures/aggregate/snowflake_with_original_granularity_multiple_aggregations.json
tests/backends/fixtures/aggregate/snowflake_with_original_granularity_multiple_aggregations_multiple_columns.json
tests/backends/fixtures/aggregate/with_original_granularity_multiple_aggregations.json
tests/backends/fixtures/aggregate/with_original_granularity_multiple_aggregations_multiple_columns.json
tests/backends/fixtures/append/domain_name_only.json
tests/backends/fixtures/append/simple.json
tests/backends/fixtures/append/with_domain_name.json
tests/backends/fixtures/comparetext/simple.json
tests/backends/fixtures/convert/snowflake.json
tests/backends/fixtures/convert/to_bool.json
tests/backends/fixtures/convert/to_datetime_from_timestamp.json
tests/backends/fixtures/convert/to_datetime.json
tests/backends/fixtures/convert/to_float.json
tests/backends/fixtures/convert/to_integer_from_datetime.json
tests/backends/fixtures/convert/to_integer.json
tests/backends/fixtures/convert/to_integer_only_floats.json
tests/backends/fixtures/convert/to_integer_only_strings.json
tests/backends/fixtures/convert/to_text.json
tests/backends/fixtures/cumsum/simple.json
tests/backends/fixtures/cumsum/with_groups.json
tests/backends/fixtures/cumsum/with_multiple_values.json
tests/backends/fixtures/custom/simple.json
tests/backends/fixtures/customsql/simple.json
tests/backends/fixtures/dateextract/after_add_missing_dates_duplicate_values.json
tests/backends/fixtures/dateextract/all_cases.json
tests/backends/fixtures/dateextract/legacy_config.json
tests/backends/fixtures/dateextract/legacy_config_without_column.json
tests/backends/fixtures/dateextract/mongo_all_cases.json
tests/backends/fixtures/dateextract/snowflake_all_cases.json
tests/backends/fixtures/delete/non_existing_column.json
tests/backends/fixtures/dissolve/pandas_advanced.json
tests/backends/fixtures/dissolve/pandas_no_aggs.json
tests/backends/fixtures/dissolve/pandas_simple.json
tests/backends/fixtures/evolution/abs_nogroups.json
tests/backends/fixtures/evolution/perc_groups.json
tests/backends/fixtures/evolution/perc_nogroups.json
tests/backends/fixtures/filter/dates_from_until.json
tests/backends/fixtures/filter/dates_from_until_strip_hours.json
tests/backends/fixtures/filter/dates.json
tests/backends/fixtures/filter/relative_dates.json
tests/backends/fixtures/formula/nested_divisions.json
tests/backends/fixtures/formula/special_col.json
tests/backends/fixtures/fromdate/day_longmonth_year_space.json
tests/backends/fixtures/fromdate/day_shortmonth_year_dash.json
tests/backends/fixtures/fromdate/day_shortmonth_year_space.json
tests/backends/fixtures/fromdate/longmonth_year_space.json
tests/backends/fixtures/fromdate/shortmonth_year_dash.json
tests/backends/fixtures/fromdate/shortmonth_year_space.json
tests/backends/fixtures/fromdate/simple.json
tests/backends/fixtures/fromdate/snowflake_simple.json
tests/backends/fixtures/hierarchy/pandas_advanced.json
tests/backends/fixtures/ifthenelse/dates-conditions.json
tests/backends/fixtures/ifthenelse/regex.json
tests/backends/fixtures/join/domain_name_only.json
tests/backends/fixtures/join/inner_geo_left.json
tests/backends/fixtures/join/inner_geo_right.json
tests/backends/fixtures/join/inner.json
tests/backends/fixtures/join/left_geo_left.json
tests/backends/fixtures/join/left_geo_right.json
tests/backends/fixtures/join/left.json
tests/backends/fixtures/join/left_outer.json
tests/backends/fixtures/movingaverage/simple.json
tests/backends/fixtures/movingaverage/with_groups.json
tests/backends/fixtures/percentage/advanced.json
tests/backends/fixtures/percentage/simple.json
tests/backends/fixtures/pivot/columns_cleaning.json
tests/backends/fixtures/pivot/simple.json
tests/backends/fixtures/rank/group_by.json
tests/backends/fixtures/rank/simple.json
tests/backends/fixtures/rank/snowflake.json
tests/backends/fixtures/replace/snowflake_simple.json
tests/backends/fixtures/rollup/groupby.json
tests/backends/fixtures/rollup/no_aggregation.json
tests/backends/fixtures/rollup/simple.json
tests/backends/fixtures/select/simple.json
tests/backends/fixtures/simplify/pandas_simple.json
tests/backends/fixtures/statistics/all.json
tests/backends/fixtures/todate/automatic_guess.json
tests/backends/fixtures/todate/from_timestamp.json
tests/backends/fixtures/todate/int_as_year_with_automatic_guess.json
tests/backends/fixtures/todate/simple.json
tests/backends/fixtures/todate/str_as_year_with_automatic_guess.json
tests/backends/fixtures/top/snowflake.json
tests/backends/fixtures/top/with_groups.json
tests/backends/fixtures/totals/simple.json
tests/backends/fixtures/totals/simple-pandas.json
tests/backends/fixtures/unpivot/pandas.json
tests/backends/fixtures/unpivot/snowflake.json
tests/backends/fixtures/waterfall/mywaterfall.json
tests/backends/fixtures/waterfall/simple.json
tests/backends/fixtures/waterfall/with_aggregation.json
tests/backends/fixtures/waterfall/with_groups.json
```

**Comment by raphaelvignes** [comment]
We won't exclude any step because of edge cases so in short what we'll exclude: 
To Exclude for redshift:
- append
- compare text
- concatenate
- cumsum
- dateextract
- dissolve
- evolution
- fromdate
- hierarchy
- join
- movingaverage
- percentage
- pivot
- rank
- rollup
- simplify
- statistics
- to_date
- totals
- unpivot
- waterfall

**Review by fspot — COMMENTED** [review]
I think the postgres test runner should keep using the old translator, because it is still the one used in laputa, and it handles more steps.
We could also have 2 postgres test runners : one for the old translator (`"postgres"`) and one for the new (`"postgres_pypika"`).

**Review by jGundermann — APPROVED** [review]
LGTM

**Pull request merged**
