### PR TITLE
feat(steps): new trim step by @CharlesRngrd

### PR DESCRIPTION
**Pull request by davinov**
Recreating this PR to add some tests fixtures + allow github actions to execute with correct credentials

### CODE REVIEW

**Comment by davinov** [comment]
Thanks @CharlesRngrd for this good work! I've testsed locally against mongo and the pandas backend. I also extracted fixtures (fecbc3a) using the how-to provided in the repo, so future backends (we're working on a SQL one now) can make use of these fixtures.
I'll get another approval from someone in the ToucanToco org (I can't approve a PR I've created) and we'll merge this soon :)

**Review by alice-sevin — APPROVED** [review]

**Comment by CharlesRngrd** [comment]
Thanks @davinov, I didn't noticed those 2 test files before ;)

**Comment by davinov** [comment]
They are new! We're making an effort to make breating backends easier. This involves extracting our test cases (fixtures) so we can share them easily bewteen backends.
https://github.com/ToucanToco/weaverbird/issues/913

**Comment by davinov** [comment]
Damn! I forgot the changelog before mergin! I'll make a quick PR for this

**Pull request merged**
