### PR TITLE
feat(playground): Added a docker-compose spec allowing to run the playground with mongo

### PR DESCRIPTION
**Pull request by lukapeschke**

### CODE REVIEW

**Review by fspot — APPROVED** [review]
Merci pour ça :ok_hand:

**Review by davinov — APPROVED** [review]
Good idea! We could also do the same for postgres
:100: 

Note: this is great to test weaverbird, but as the images are built (the code not linked), it's not suited very well for development

**Comment by lukapeschke** [comment]
> Good idea! We could also do the same for postgres 100

You're right, I'll add it.

> Note: this is great to test weaverbird, but as the images are built (the code not linked), it's not suited very well for development

I wasn't really sure about how to link the code since `yarn build` is quite long... Or I can just add a volume with the python sources, run `pip install` in the entrypoint and specify in the docs that the image needs to be rebuilt in order to test any frontend change ?

**Comment by Sanix-Darker** [comment]
i think the idea with 'volumes' is good IMO !

**Comment by lukapeschke** [comment]
@Sanix-Darker added the make targets you requested

**Review by Sanix-Darker — APPROVED** [review]

**Pull request merged**
