### PR TITLE
feat(vqb-step): added convert (CAST) translator step

### PR DESCRIPTION
**Pull request by Sanix-Darker**
# Summary
- Added the `convert` (known as `CAST`) step in sql_translator.
- Wrote tests of `translate_convert`.

Interface | Weaverbird (local pc) | Snowflake (query history)
--- | --- | --- 
Screenshot | Screenshot from 2021-08-13 17-50-26 | Screenshot from 2021-08-13 17-50-59
 
# Checks
- [x] Unit tests

### CODE REVIEW

**Comment by Sanix-Darker** [comment]
[(2) [Snowflake SQL VQB] - Convert Step - CAST](https://trello.com/c/iDmvxo0g/1121-2-snowflake-sql-vqb-convert-step-cast)

**Comment by Sanix-Darker** [comment]
[(2) [Snowflake SQL VQB] - Convert Step - CAST](https://trello.com/c/iDmvxo0g/1121-2-snowflake-sql-vqb-convert-step-cast)

**Comment by Sanix-Darker** [comment]
[(2) [Snowflake SQL VQB] - Convert Step - CAST](https://trello.com/c/iDmvxo0g/1121-2-snowflake-sql-vqb-convert-step-cast)

**Comment by Sanix-Darker** [comment]
[(2) [Snowflake SQL VQB] - Convert Step - CAST](https://trello.com/c/iDmvxo0g/1121-2-snowflake-sql-vqb-convert-step-cast)

**Comment by Sanix-Darker** [comment]
[(2) [Snowflake SQL VQB] - Convert Step - CAST](https://trello.com/c/iDmvxo0g/1121-2-snowflake-sql-vqb-convert-step-cast)

**Review by f-bb-toucantoco — APPROVED** [review]

**Pull request merged**
